### ISSUE TITLE
fxa-admins must have 2FA enabled on their Github accounts

### ISSUE THREAD

**Issue by ckarlof** [mozilla/fxa-content-experiments#12]
This list includes: @vladikoff @jrgm @shane-tomlinson @dannycoates and @rfk 

For context: https://github.com/mozilla/fxa-content-experiments/issues/10#issuecomment-113305882

**Comment by jrgm** [comment]
my github has been 2FA enabled since way back. 

(Sidenote: isn't 2FA mandatory for all fxa repositories?)

**Comment by rfk** [comment]
Checking the moz org people view, it looks like @dannycoates is the only one without.

**Comment by dannycoates** [comment]
ok, fine

but seriously :fu: 2FA

**Comment by vladikoff** [comment]
thanks @dannycoates !
