### ISSUE TITLE
add eslint to this repo

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-experiments#13]
Would it be a good idea to stabilize the styling for the experiments?

**Comment by pdehaan** [comment]
@vladikoff Seems easy enough. Very few files so far, everybody seems consistent w/ single quotes, semi colons, 'use strict', etc.

**Comment by TDA** [comment]
@vladikoff @pdehaan yayyy! MINE!!!

**Comment by vladikoff** [comment]
@dannycoates any objections to adding devDeps to this repo?

**Comment by dannycoates** [comment]
> any objections to adding devDeps to this repo?

no objections
