### ISSUE TITLE
Fully enable avatar feature flag when Fx41 hits beta

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-content-experiments#21]
Ref: https://github.com/mozilla/fxa-content-server/issues/1582#issuecomment-121408659

Avatars are shipping in browser chrome in Fx41, so we need to pref on the avatar settings link before then.  IIUC we can pre-configure an experiment to enable automatically on some future date, so it's probably worth doing that and then we can forget about it and let it ride the trains.

**Comment by vladikoff** [comment]
@rfk @edmoz Could you let me know what exact date we should set that to?

**Comment by rfk** [comment]
Fx41 moves to beta week of August 11.  IIUC the plan is to enable this link for all users as of that date (even users on the release channel).  @edmoz please confirm.

**Comment by rfk** [comment]
I notice @edmoz was not auto-completing for the @-mention, so it's not clear whether he would have been summonned in here by the above comment.   I added a "fxa-readonly" team to this repo to make sure he's got appropriate visibility.

**Comment by edwindotcom** [comment]
damn email filters... 
Yes, August 11 is Beta uplift day.  Beta usually takes an extra day to get posted, so let's say Wednesday, August 12th at 10am PDT.

**Comment by rfk** [comment]
Should we try to err on the side of enabling earlier than beta, or later than beta?  ISTM we should lean towards earlier but I don't have much context on the discussions.

**Comment by rfk** [comment]
Let's target August 11 to be sure it's enabled before beta, but not too much before.
