### ISSUE TITLE
document branch/deploy procedure for experiments repo

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-content-experiments#29]
As @shane-tomlinson describes in https://github.com/mozilla/fxa-content-experiments/pull/25#issuecomment-148657212, we have some process and convention around how the experiments in this repo get to production, but it's not obvious where to go to find out about it.  Let's add some docs if we don't have them, and a link from the README.

**Comment by vladikoff** [comment]
from mtg: will document!
