### ISSUE TITLE
warning: bug in github url parser

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-content-experiments#4]
:warning:  @shane-tomlinson @dannycoates quick note:
We use the following configuration in the content server

``` js
experiments: {
  dir: {
    doc: 'path to where experiments are stored',
    default: path.resolve(__dirname, '..', '..', 'experiments')
  },
  git: {
    doc: 'git url for experiments repo. set to empty to not pull',
    default: 'git://github.com/mozilla/fxa-content-experiments.git#master'  <=== this
  },
  watch: {
    doc: 'poll the experiments git repo for changes',
    default: false
  }
},
```

The `experiments.git` setting will not correctly parse if the branch is changed from `#master` to anything else. 

ref https://github.com/dannycoates/able/blob/master/project.js#L4
ref https://github.com/zeke/github-url-to-object/issues/9

**Comment by vladikoff** [comment]
closing because this is just a notice

**Comment by dannycoates** [comment]
Thanks @vladikoff. I think in the interim we can use the shorthand version, `github:mozilla/fxa-content-experiments#foo`
